#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -gt 2 ]; then
  echo "Usage: bless-client-baseline.sh [results-dir [baseline-file]]" >&2
  exit 2
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/../.." && pwd)"
results_dir="${1:-${repo_root}/conformance-results/client}"
baseline_file="${2:-${script_dir}/client-expected-failures.yml}"
scenarios=(tools_call request-metadata http-standard-headers http-custom-headers)

for command in awk cmp cp jq mktemp sed sort; do
  if ! command -v "${command}" > /dev/null 2>&1; then
    echo "Required command not found: ${command}" >&2
    exit 2
  fi
done
if [ ! -d "${results_dir}" ]; then
  echo "No client conformance results directory: ${results_dir}" >&2
  exit 2
fi
if [ ! -f "${baseline_file}" ]; then
  echo "Client conformance baseline not found: ${baseline_file}" >&2
  exit 2
fi

state_dir="$(mktemp -d "${TMPDIR:-/tmp}/contextforge-client-baseline.XXXXXX")"
findings="${state_dir}/findings.txt"
baseline_entries="${state_dir}/baseline-entries.txt"
candidate="${state_dir}/client-expected-failures.yml"

cleanup() {
  rm -f -- "${findings}" "${baseline_entries}" "${candidate}"
  rmdir -- "${state_dir}"
}
trap cleanup EXIT INT TERM

: > "${findings}"
for scenario in "${scenarios[@]}"; do
  matches=("${results_dir}/${scenario}-"*/checks.json)
  if [ ! -e "${matches[0]}" ]; then
    echo "No client conformance results found for scenario: ${scenario}" >&2
    exit 2
  fi
  checks_file="${matches[$((${#matches[@]} - 1))]}"
  jq --raw-output --arg scenario "${scenario}" '
    def severity($status):
      if $status == "FAILURE" then 3
      elif $status == "WARNING" then 2
      elif $status == "SUCCESS" then 1
      else 0
      end;

    reduce (.[] | select(.status != "INFO")) as $check
      ({};
       ($check.id) as $id |
       if .[$id] == null or severity($check.status) >= severity(.[$id].status)
       then .[$id] = $check
       else .
       end) |
    to_entries[] |
    select(.value.status == "FAILURE" or .value.status == "WARNING") |
    ($scenario + ":" + .key)
  ' "${checks_file}" >> "${findings}"
done
LC_ALL=C sort -u -o "${findings}" "${findings}"

awk '
  /^client:$/ { in_client = 1; next }
  in_client && /^[^[:space:]]/ { exit }
  in_client && /^[[:space:]]*-[[:space:]]+/ {
    line = $0
    sub(/^[[:space:]]*-[[:space:]]+/, "", line)
    sub(/[[:space:]]+#.*$/, "", line)
    print line
  }
' "${baseline_file}" | LC_ALL=C sort -u > "${baseline_entries}"

{
  # shellcheck disable=SC2016 # Backticks are literal Markdown.
  echo '# Generated by `make conformance-bless` from scoped client findings.'
  echo '# OAuth client scenarios are control-plane responsibilities and are not run here.'
  if [ -s "${findings}" ]; then
    echo 'client:'
    sed 's/^/  - /' "${findings}"
  else
    echo 'client: []'
  fi
} > "${candidate}"

if cmp --silent "${findings}" "${baseline_entries}"; then
  echo "Client conformance baseline was already current: ${baseline_file}"
else
  cp "${candidate}" "${baseline_file}"
  echo "Client conformance baseline updated: ${baseline_file}"
fi
