#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
state_dir="$(mktemp -d "${TMPDIR:-/tmp}/contextforge-client-baseline-test.XXXXXX")"
results_dir="${state_dir}/results"
baseline_file="${state_dir}/client-expected-failures.yml"

cleanup() {
  rm -rf -- "${state_dir}"
}
trap cleanup EXIT INT TERM

mkdir -p \
  "${results_dir}/tools_call-2026-08-20T00-00-00-000Z" \
  "${results_dir}/request-metadata-2026-08-20T00-00-00-000Z" \
  "${results_dir}/http-standard-headers-2026-08-20T00-00-00-000Z" \
  "${results_dir}/http-custom-headers-2026-08-20T00-00-00-000Z"

cat > "${baseline_file}" <<'EOF'
client: []
EOF
for scenario in tools_call request-metadata http-standard-headers; do
  cat > "${results_dir}/${scenario}-2026-08-20T00-00-00-000Z/checks.json" <<'EOF'
[{"id":"passes","status":"SUCCESS"}]
EOF
done
cat > "${results_dir}/http-custom-headers-2026-08-20T00-00-00-000Z/checks.json" <<'EOF'
[
  {"id":"mirrors","status":"SUCCESS"},
  {"id":"mirrors","status":"FAILURE"},
  {"id":"encodes","status":"WARNING"},
  {"id":"omits-null","status":"SUCCESS"}
]
EOF

"${script_dir}/bless-client-baseline.sh" "${results_dir}" "${baseline_file}"

cat > "${state_dir}/expected.yml" <<'EOF'
# Generated by `make conformance-bless` from scoped client findings.
# OAuth client scenarios are control-plane responsibilities and are not run here.
client:
  - http-custom-headers:encodes
  - http-custom-headers:mirrors
EOF
diff -u "${state_dir}/expected.yml" "${baseline_file}"

second_output="$("${script_dir}/bless-client-baseline.sh" "${results_dir}" "${baseline_file}")"
grep --fixed-strings --quiet -- 'was already current' <<< "${second_output}"

echo 'client conformance baseline tests passed'
