
[package]
name = "contextforge-data-plane-apis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true


[dependencies]
cpex.workspace = true
serde= {workspace = true, features=["derive"]}
serde_json.workspace = true
url = { workspace = true }
schemars = { version = "1.2.2", features = ["url2", "preserve_order"] }
rmcp.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false
