[package]
name = "contextforge-data-plane-observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
http.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp = { version = "0.32", default-features = false, features = ["grpc-tonic", "http-proto", "reqwest-blocking-client", "trace", "metrics", "internal-logs", "tls-aws-lc"] }
opentelemetry_sdk.workspace = true
tonic = { version = "0.14", default-features = false }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "tracing-log"] }

[lints]
workspace = true

[lib]
doctest = false
